version: '3.5'

networks:
  happycattle:
    name: happycattle
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.1.0/16

secrets:
  happycattle_key:
    file: "${HAPPYCATTLE_TOKEN_KEY_FILE}"
  happycattle_cert:
    file: "${HAPPYCATTLE_TOKEN_CRT_FILE}"

services:
  happycattle-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: happycattle-elasticsearch
    environment:
      - discovery.type=single-node
      - transport.publish_port=9200
    networks:
      happycattle:
        ipv4_address: 10.2.1.2
        aliases:
          - happycattle-elasticsearch.docker
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3

  happycattle-mongo:
    image: mongo:3.6.21
    container_name: happycattle-mongo
    networks:
      happycattle:
        ipv4_address: 10.2.1.3
        aliases:
          - happycattle-mongo.docker
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mongo.env
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/01_init-mongo.js:ro
      - ./db/init-mongo-dump.sh:/docker-entrypoint-initdb.d/02_init-mongo-dump.sh:ro
      - ./db/api_umbrella:/dump/api_umbrella

  happycattle-mysql:
    image: mysql:5.7
    container_name: happycattle-mysql
    networks:
      happycattle:
        ipv4_address: 10.2.1.4
        aliases:
          - happycattle-mysql.docker
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -P 8152 -u root -proot --silent"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mysql.env
    volumes:
      - ./db/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql

  happycattle-keyrock:
    image: fiware/idm:i4trust-rc6
    container_name: happycattle-keyrock
    networks:
      happycattle:
        ipv4_address: 10.2.1.20
        aliases:
          - happycattle-keyrock.docker
    depends_on:
      - happycattle-mysql
    entrypoint: /init/init-keyrock.sh
    env_file:
      - ./envs/keyrock.env
    secrets:
      - happycattle_key
      - happycattle_cert
    environment:
      - HAPPYCATTLE_EORI
      - HAPPYCATTLE_TOKEN_KEY_CONTENT
      - HAPPYCATTLE_TOKEN_CRT_CONTENT
      - HAPPYCATTLE_TOKEN_KEY_FILE
      - HAPPYCATTLE_TOKEN_CRT_FILE
    volumes:
      - ./init/init-keyrock.sh:/init/init-keyrock.sh

  happycattle-umbrella:
    image: fiware/api-umbrella:0.18.0
    container_name: happycattle-umbrella
    networks:
      happycattle:
        ipv4_address: 10.2.1.30
        aliases:
          - happycattle-umbrella.docker
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost/api-umbrella/v1/health | python -mjson.tool | grep '\"status\": \"green\"' || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - happycattle-mongo
    entrypoint: /init/init-umbrella.sh
    secrets:
      - happycattle_key
      - happycattle_cert
    environment:
      - HAPPYCATTLE_EORI
      - HAPPYCATTLE_TOKEN_KEY_CONTENT
      - HAPPYCATTLE_TOKEN_CRT_CONTENT
      - HAPPYCATTLE_TOKEN_KEY_FILE
      - HAPPYCATTLE_TOKEN_CRT_FILE
    volumes:
      - ./init/init-umbrella.sh:/init/init-umbrella.sh
      - ./umbrella-conf/api-umbrella.template.yml:/etc/api-umbrella/api-umbrella.template.yml
    tmpfs:
      # Mount the ember-cli tmp directory as a tmpfs partition for better
      # performance.
      - /app/src/api-umbrella/admin-ui/tmp:rw,size=128m,mode=1777

  happycattle-orion:
    image: quay.io/fiware/orion-ld:1.0.1
    container_name: happycattle-orion
    networks:
      happycattle:
        ipv4_address: 10.2.1.40
        aliases:
          - happycattle-orion.docker
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:1026/version || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - happycattle-mongo
    env_file:
      - ./envs/orion.env
    command: -dbhost happycattle-mongo.docker -logLevel DEBUG
      
