version: '3.5'

#networks:
#  bae:
#    name: bae
#    external: false

services:
  bae-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: bae-elasticsearch
    environment:
      - discovery.type=single-node
      - transport.publish_port=8150
    #ports:
    #  - "127.0.0.1:8150:9200"
    #networks:
    #  bae:
    #    aliases:
    #      - bae-elasticsearch.docker
    network_mode: host
    #ports:
    #  - 8150:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
              
  bae-mongo:
    image: mongo:3.6.21
    container_name: bae-mongo
    #networks:
    #  bae:
    #    aliases:
    #      - bae-mongo.docker
    network_mode: host
    command: --port 8151
    #ports:
    #  - 8151:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mongo.env
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  bae-mysql:
    image: mysql:5.7
    container_name: bae-mysql
    #networks:
    #  bae:
    #    aliases:
    #      - bae-mysql.docker
    network_mode: host
    #ports: # Need to configure port via app itself TODO
    #  - 8152:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -P 8152 -u root -proot --silent"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mysql.env
    volumes:
      - ./db/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql

  bae-keyrock:
    image: fiware/idm:8.1.0
    container_name: bae-keyrock
    #networks:
    #  bae:
    #    aliases:
    #      - bae-keyrock.docker
    network_mode: host
    depends_on:
      - bae-mysql
    #ports:
    #  - 8100:8080
    env_file:
      - ./envs/keyrock.env
      
  bae-apis:
    image: fiware/biz-ecosystem-apis:v7.6.0
    container_name: bae-apis
    depends_on:
      - bae-mysql
    entrypoint: /init/init-apis.sh
    #networks:
    #  bae:
    #    aliases:
    #      - bae-apis.docker
    network_mode: host
    #ports:
    #  - 8110:8080
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost:8110/DSProductInventory"]
      start_period: 120s
      interval: 30s
      timeout: 30s
      retries: 1
    env_file:
      - ./envs/apis.env
    volumes:
      - ./init/init-apis.sh:/init/init-apis.sh
      - ./apis-override/entrypoint.sh:/entrypoint.sh
      - ./apis-override/apis-entrypoint.py:/apis-entrypoint.py

  bae-rss:
    image: fiware/biz-ecosystem-rss:v8.0.0
    container_name: bae-rss
    depends_on:
      - bae-mysql
      - bae-apis
    entrypoint: /init/init-rss.sh
    #networks:
    #  bae:
    #    aliases:
    #      - bae-rss.docker
    network_mode: host
    #ports:
    #  - 8120:8080
    healthcheck:
      test: ["CMD", "/glassfish4/glassfish/bin/asadmin", "show-component-status", "DSRevenueSharing"]
      start_period: 120s
      interval: 30s
      timeout: 30s
      retries: 1
    volumes:
      - ./init/init-rss.sh:/init/init-rss.sh
    env_file:
      - ./envs/rss.env

  bae-charging:
    image: fiware/biz-ecosystem-charging-backend:v8.0.0
    container_name: bae-charging
    depends_on:
      - bae-mongo
      - bae-apis
    entrypoint: /init/init-charging.sh
    #networks:
    #  bae:
    #    aliases:
    #      - bae-charging.docker
    network_mode: host
    #ports:
    #  - 8106:8006
    healthcheck:
      test: ["CMD", "wget", "-q", "http://bae-charging.docker:8106/charging/api/assetManagement/currencyCodes"]
      start_period: 180s
      interval: 30s
      timeout: 30s
      retries: 1
    volumes:
      - ./init/init-charging.sh:/init/init-charging.sh
      - ./charging-override/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./envs/charging.env

  bae-proxy:
    image: fiware/biz-ecosystem-logic-proxy:v8.0.0
    container_name: bae-proxy
    depends_on:
      - bae-mongo
      - bae-apis
      - bae-rss
      - bae-charging
    entrypoint: /init/init-proxy.sh
    #networks:
    #  bae:
    #    aliases:
    #      - bae-proxy.docker
    network_mode: host
    #ports:
    #  - 8104:8004
    volumes:
      - ./init/init-proxy.sh:/init/init-proxy.sh
    env_file:
      - ./envs/proxy.env
