version: '3.5'

networks:
  shepherd:
    name: shepherd
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.2.0/16

secrets:
  shepherd_key:
    file: "${SHEPHERD_TOKEN_KEY_FILE}"
  shepherd_cert:
    file: "${SHEPHERD_TOKEN_CRT_FILE}"

services:
  shepherd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: shepherd-elasticsearch
    environment:
      - discovery.type=single-node
      - transport.publish_port=9200
    networks:
      shepherd:
        ipv4_address: 10.2.2.2
        aliases:
          - shepherd-elasticsearch.docker
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3

  shepherd-mongo:
    image: mongo:3.6.21
    container_name: shepherd-mongo
    networks:
      shepherd:
        ipv4_address: 10.2.2.3
        aliases:
          - shepherd-mongo.docker
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mongo.env
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/01_init-mongo.js:ro
      - ./db/init-mongo-dump.sh:/docker-entrypoint-initdb.d/02_init-mongo-dump.sh:ro
      - ./db/api_umbrella:/dump/api_umbrella

  shepherd-mysql:
    image: mysql:5.7
    container_name: shepherd-mysql
    networks:
      shepherd:
        ipv4_address: 10.2.2.4
        aliases:
          - shepherd-mysql.docker
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -P 8152 -u root -proot --silent"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./envs/mysql.env
    volumes:
      - ./db/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql

  shepherd-keyrock:
    image: fiware/idm:i4trust-rc6
    container_name: shepherd-keyrock
    networks:
      shepherd:
        ipv4_address: 10.2.2.20
        aliases:
          - shepherd-keyrock.docker
    depends_on:
      - shepherd-mysql
    entrypoint: /init/init-keyrock.sh
    env_file:
      - ./envs/keyrock.env
    secrets:
      - shepherd_key
      - shepherd_cert
    environment:
      - SHEPHERD_EORI
      - SHEPHERD_TOKEN_KEY_CONTENT
      - SHEPHERD_TOKEN_CRT_CONTENT
      - SHEPHERD_TOKEN_KEY_FILE
      - SHEPHERD_TOKEN_CRT_FILE
    volumes:
      - ./init/init-keyrock.sh:/init/init-keyrock.sh

  shepherd-umbrella:
    image: fiware/api-umbrella:0.18.0
    container_name: shepherd-umbrella
    networks:
      shepherd:
        ipv4_address: 10.2.2.30
        aliases:
          - shepherd-umbrella.docker
    depends_on:
      - shepherd-mongo
    entrypoint: /init/init-umbrella.sh
    secrets:
      - shepherd_key
      - shepherd_cert
    environment:
      - SHEPHERD_EORI
      - SHEPHERD_TOKEN_KEY_CONTENT
      - SHEPHERD_TOKEN_CRT_CONTENT
      - SHEPHERD_TOKEN_KEY_FILE
      - SHEPHERD_TOKEN_CRT_FILE
    volumes:
      - ./init/init-umbrella.sh:/init/init-umbrella.sh
      - ./umbrella-conf/api-umbrella.template.yml:/etc/api-umbrella/api-umbrella.template.yml
    tmpfs:
      # Mount the ember-cli tmp directory as a tmpfs partition for better
      # performance.
      - /app/src/api-umbrella/admin-ui/tmp:rw,size=128m,mode=1777

  shepherd-orion:
    image: quay.io/fiware/orion-ld:1.0.1
    container_name: shepherd-orion
    networks:
      shepherd:
        ipv4_address: 10.2.2.40
        aliases:
          - shepherd-orion.docker
    depends_on:
      - shepherd-mongo
    env_file:
      - ./envs/orion.env
    command: -dbhost shepherd-mongo.docker -logLevel DEBUG
      
