name: Integration-test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Run compose
      id: compose
      run: |
        cd docker
        docker-compose -f docker-compose.yml -f smart-shepherd/docker-compose.yml -f happycattle/docker-compose.yml up -d
        
    - name: Run tests
      id: test
      run: |
        cd it/
        mvn clean install -Dcucumber.publish-token=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

    - name: Collect logs
      if: ${{ failure() }}
      run: |
        cd docker
        docker-compose -f docker-compose.yml -f smart-shepherd/docker-compose.yml -f happycattle/docker-compose.yml logs